services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ${DB_PASSWORD}
      ACCEPT_EULA: "Y"
      MSSQL_DB: ${DB_NAME}
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
