CREATE OR REPLACE VIEW "Update_Customer_Info"."Newcustomerinfo" AS
 WITH clean_info AS (
         SELECT DISTINCT cd.id,
            cd.ten_khach_hang,
            cd.pid,
            cd.gioi_tinh,
            cd.ngay_sinh,
            cd.chuyen_vien_tu_van,
            cd.muc_do,
            cd.nguon_1,
            cd.nguoi_gioi_thieu_id,
            cd.nguoi_gioi_thieu_khach_hang_pid,
            cd.nguoi_gioi_thieu_khach_hang,
            cd.nguoi_gioi_thieu_noi_bo,
            cd.co_phuc_loi_tap_doan,
            cd.cap_quyen_loi_ap_dung,
            cd.cong_ty_1,
            cd.ten_bao_hiem_thanh_toan,
            cd.quan_he_voi_cap_quyen_loi_ap_dung,
            cd.ngay_cuoi_cap_nhat,
            (cd.ngay_cuoi_cap_nhat)::date AS "Ngayudpate",
            row_number() OVER (PARTITION BY cd.id ORDER BY cd.ngay_cuoi_cap_nhat DESC) AS "Ngaymoinhat"
           FROM customer_data cd
        ), rank_info AS (
         SELECT clean_info.id,
            clean_info.ten_khach_hang,
            clean_info.pid,
            clean_info.gioi_tinh,
            clean_info.ngay_sinh,
            clean_info.chuyen_vien_tu_van,
            clean_info.muc_do,
            clean_info.nguon_1,
            clean_info.nguoi_gioi_thieu_id,
            clean_info.nguoi_gioi_thieu_khach_hang_pid,
            clean_info.nguoi_gioi_thieu_khach_hang,
            clean_info.nguoi_gioi_thieu_noi_bo,
            clean_info.co_phuc_loi_tap_doan,
            clean_info.cap_quyen_loi_ap_dung,
            clean_info.cong_ty_1,
            clean_info.ten_bao_hiem_thanh_toan,
            clean_info.quan_he_voi_cap_quyen_loi_ap_dung,
            clean_info.ngay_cuoi_cap_nhat,
            clean_info."Ngayudpate",
            clean_info."Ngaymoinhat"
           FROM clean_info
          WHERE (clean_info."Ngaymoinhat" = 1)
        )
 SELECT id,
    ten_khach_hang,
    pid,
    gioi_tinh,
    ngay_sinh,
    chuyen_vien_tu_van,
    muc_do,
    nguon_1,
    nguoi_gioi_thieu_id,
    nguoi_gioi_thieu_khach_hang_pid,
    nguoi_gioi_thieu_khach_hang,
    nguoi_gioi_thieu_noi_bo,
    co_phuc_loi_tap_doan,
    cap_quyen_loi_ap_dung,
    cong_ty_1,
    ten_bao_hiem_thanh_toan,
    quan_he_voi_cap_quyen_loi_ap_dung,
    ngay_cuoi_cap_nhat,
    "Ngayudpate",
    "Ngaymoinhat"
   FROM rank_info;